services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: "False"
      ALLOWED_HOSTS: "*"
    ports:
      - "8000:8000"
    command: bash -c "./wait-for-it.sh ${DATABASE_HOST}:${DATABASE_PORT} -- python backend/setup_db.py && python backend/app/manage.py runserver 0.0.0.0:8000"
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      NODE_ENV: "production"
    ports:
      - "3000:3000"
volumes:
  pgdata: